services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - ../.env
    ports:
      - "18000:8000"
    volumes:
      - ../:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - network_deep_tech_doc_scope
    restart: always

  postgres:
    image: postgres:17-alpine
    env_file:
      - ../.env
    ports:
      - "15432:5432"
    volumes:
      - ../../DB/postgres/pg_data_deep_tech_doc_scope/:/var/lib/postgres/data
    networks:
      - network_deep_tech_doc_scope
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user_doc_scope} -d ${POSTGRES_DB:-db_doc_scope}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "16379:6379"
    networks:
      - network_deep_tech_doc_scope
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A config worker -l info
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - network_deep_tech_doc_scope
    restart: always
    healthcheck:
      test: ["CMD", "celery", "-A", "config", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - network_deep_tech_doc_scope
    restart: always
    healthcheck:
      test: ["CMD", "celery", "-A", "config", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pg_data_deep_tech_doc_scope:

networks:
  network_deep_tech_doc_scope:
    driver: bridge